{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from futu import *\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 09:15:40,513 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 09:15:41,135 [open_context_base.py] on_connected:344: Connected : conn_id=11; \n",
      "2019-07-29 09:15:41,189 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=11; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561413734177839042, 'conn_key': 'B98F120207D30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n"
     ]
    }
   ],
   "source": [
    "quote_ctx = OpenQuoteContext(host='futuapi.mkmerich.com', port=54012)\n",
    "ret, data, page_req_key = quote_ctx.request_history_kline('SH.601127', start='2019-01-01', end='2019-07-26',\n",
    "                                                          ktype=KLType.K_60M, fields=[KL_FIELD.DATE_TIME, KL_FIELD.CLOSE], max_count=50) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>code</th>\n",
       "      <th>time_key</th>\n",
       "      <th>close</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-02 10:30:00</td>\n",
       "      <td>16.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-02 11:30:00</td>\n",
       "      <td>16.54</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-02 14:00:00</td>\n",
       "      <td>16.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-02 15:00:00</td>\n",
       "      <td>16.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-03 10:30:00</td>\n",
       "      <td>16.45</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-03 11:30:00</td>\n",
       "      <td>16.07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-03 14:00:00</td>\n",
       "      <td>15.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-03 15:00:00</td>\n",
       "      <td>16.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-04 10:30:00</td>\n",
       "      <td>16.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-04 11:30:00</td>\n",
       "      <td>16.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-04 14:00:00</td>\n",
       "      <td>16.13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-04 15:00:00</td>\n",
       "      <td>16.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-07 10:30:00</td>\n",
       "      <td>16.21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-07 11:30:00</td>\n",
       "      <td>16.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-07 14:00:00</td>\n",
       "      <td>16.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-07 15:00:00</td>\n",
       "      <td>16.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-08 10:30:00</td>\n",
       "      <td>16.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-08 11:30:00</td>\n",
       "      <td>16.22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-08 14:00:00</td>\n",
       "      <td>16.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-08 15:00:00</td>\n",
       "      <td>16.29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-09 10:30:00</td>\n",
       "      <td>16.63</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-09 11:30:00</td>\n",
       "      <td>16.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-09 14:00:00</td>\n",
       "      <td>16.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-09 15:00:00</td>\n",
       "      <td>16.58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-10 10:30:00</td>\n",
       "      <td>16.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-10 11:30:00</td>\n",
       "      <td>16.60</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-10 14:00:00</td>\n",
       "      <td>16.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-10 15:00:00</td>\n",
       "      <td>16.46</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-11 10:30:00</td>\n",
       "      <td>16.33</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-11 11:30:00</td>\n",
       "      <td>16.36</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-11 14:00:00</td>\n",
       "      <td>16.39</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-11 15:00:00</td>\n",
       "      <td>16.49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-14 10:30:00</td>\n",
       "      <td>16.53</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-14 11:30:00</td>\n",
       "      <td>16.64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-14 14:00:00</td>\n",
       "      <td>16.67</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-14 15:00:00</td>\n",
       "      <td>16.63</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-15 10:30:00</td>\n",
       "      <td>16.67</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-15 11:30:00</td>\n",
       "      <td>16.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-15 14:00:00</td>\n",
       "      <td>16.65</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-15 15:00:00</td>\n",
       "      <td>16.64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-16 10:30:00</td>\n",
       "      <td>16.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-16 11:30:00</td>\n",
       "      <td>16.54</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-16 14:00:00</td>\n",
       "      <td>16.64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-16 15:00:00</td>\n",
       "      <td>16.58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-17 10:30:00</td>\n",
       "      <td>16.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-17 11:30:00</td>\n",
       "      <td>16.65</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-17 14:00:00</td>\n",
       "      <td>16.70</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-17 15:00:00</td>\n",
       "      <td>16.68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-18 10:30:00</td>\n",
       "      <td>16.58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>SH.601127</td>\n",
       "      <td>2019-01-18 11:30:00</td>\n",
       "      <td>16.54</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         code             time_key  close\n",
       "0   SH.601127  2019-01-02 10:30:00  16.57\n",
       "1   SH.601127  2019-01-02 11:30:00  16.54\n",
       "2   SH.601127  2019-01-02 14:00:00  16.62\n",
       "3   SH.601127  2019-01-02 15:00:00  16.62\n",
       "4   SH.601127  2019-01-03 10:30:00  16.45\n",
       "5   SH.601127  2019-01-03 11:30:00  16.07\n",
       "6   SH.601127  2019-01-03 14:00:00  15.96\n",
       "7   SH.601127  2019-01-03 15:00:00  16.00\n",
       "8   SH.601127  2019-01-04 10:30:00  16.09\n",
       "9   SH.601127  2019-01-04 11:30:00  16.16\n",
       "10  SH.601127  2019-01-04 14:00:00  16.13\n",
       "11  SH.601127  2019-01-04 15:00:00  16.12\n",
       "12  SH.601127  2019-01-07 10:30:00  16.21\n",
       "13  SH.601127  2019-01-07 11:30:00  16.16\n",
       "14  SH.601127  2019-01-07 14:00:00  16.12\n",
       "15  SH.601127  2019-01-07 15:00:00  16.12\n",
       "16  SH.601127  2019-01-08 10:30:00  16.12\n",
       "17  SH.601127  2019-01-08 11:30:00  16.22\n",
       "18  SH.601127  2019-01-08 14:00:00  16.18\n",
       "19  SH.601127  2019-01-08 15:00:00  16.29\n",
       "20  SH.601127  2019-01-09 10:30:00  16.63\n",
       "21  SH.601127  2019-01-09 11:30:00  16.61\n",
       "22  SH.601127  2019-01-09 14:00:00  16.62\n",
       "23  SH.601127  2019-01-09 15:00:00  16.58\n",
       "24  SH.601127  2019-01-10 10:30:00  16.62\n",
       "25  SH.601127  2019-01-10 11:30:00  16.60\n",
       "26  SH.601127  2019-01-10 14:00:00  16.47\n",
       "27  SH.601127  2019-01-10 15:00:00  16.46\n",
       "28  SH.601127  2019-01-11 10:30:00  16.33\n",
       "29  SH.601127  2019-01-11 11:30:00  16.36\n",
       "30  SH.601127  2019-01-11 14:00:00  16.39\n",
       "31  SH.601127  2019-01-11 15:00:00  16.49\n",
       "32  SH.601127  2019-01-14 10:30:00  16.53\n",
       "33  SH.601127  2019-01-14 11:30:00  16.64\n",
       "34  SH.601127  2019-01-14 14:00:00  16.67\n",
       "35  SH.601127  2019-01-14 15:00:00  16.63\n",
       "36  SH.601127  2019-01-15 10:30:00  16.67\n",
       "37  SH.601127  2019-01-15 11:30:00  16.72\n",
       "38  SH.601127  2019-01-15 14:00:00  16.65\n",
       "39  SH.601127  2019-01-15 15:00:00  16.64\n",
       "40  SH.601127  2019-01-16 10:30:00  16.62\n",
       "41  SH.601127  2019-01-16 11:30:00  16.54\n",
       "42  SH.601127  2019-01-16 14:00:00  16.64\n",
       "43  SH.601127  2019-01-16 15:00:00  16.58\n",
       "44  SH.601127  2019-01-17 10:30:00  16.59\n",
       "45  SH.601127  2019-01-17 11:30:00  16.65\n",
       "46  SH.601127  2019-01-17 14:00:00  16.70\n",
       "47  SH.601127  2019-01-17 15:00:00  16.68\n",
       "48  SH.601127  2019-01-18 10:30:00  16.58\n",
       "49  SH.601127  2019-01-18 11:30:00  16.54"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 10:25:49,266 [network_manager.py] _on_packet:562: Recv: conn_id=19; proto_id=1004; serial_no=9583; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:49,271 [network_manager.py] _on_packet:562: Recv: conn_id=21; proto_id=1004; serial_no=9584; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:49,275 [network_manager.py] _on_packet:562: Recv: conn_id=22; proto_id=1004; serial_no=9585; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:52,507 [network_manager.py] _on_packet:562: Recv: conn_id=23; proto_id=1004; serial_no=9586; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:57,293 [network_manager.py] _on_packet:562: Recv: conn_id=20; proto_id=1004; serial_no=9587; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:57,300 [network_manager.py] _on_packet:562: Recv: conn_id=19; proto_id=1004; serial_no=9588; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:57,308 [network_manager.py] _on_packet:562: Recv: conn_id=21; proto_id=1004; serial_no=9589; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:25:57,317 [network_manager.py] _on_packet:562: Recv: conn_id=22; proto_id=1004; serial_no=9590; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:00,515 [network_manager.py] _on_packet:562: Recv: conn_id=23; proto_id=1004; serial_no=9591; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:05,329 [network_manager.py] _on_packet:562: Recv: conn_id=20; proto_id=1004; serial_no=9592; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:05,336 [network_manager.py] _on_packet:562: Recv: conn_id=19; proto_id=1004; serial_no=9593; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:05,343 [open_context_base.py] _handle_keep_alive:459: Fail to recv KeepAlive for 3 times\n",
      "2019-07-29 10:26:05,350 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:05,358 [network_manager.py] _on_packet:562: Recv: conn_id=21; proto_id=1004; serial_no=9594; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:05,366 [network_manager.py] _on_packet:562: Recv: conn_id=22; proto_id=1004; serial_no=9595; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:05,374 [open_context_base.py] _handle_keep_alive:459: Fail to recv KeepAlive for 3 times\n",
      "2019-07-29 10:26:05,381 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:06,302 [open_context_base.py] on_error:365: Connect error: conn_id=23; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:06,308 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:06,321 [open_context_base.py] on_error:365: Connect error: conn_id=23; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:13,357 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:13,391 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:13,394 [network_manager.py] _on_packet:562: Recv: conn_id=20; proto_id=1004; serial_no=9597; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:13,455 [network_manager.py] _on_packet:562: Recv: conn_id=21; proto_id=1004; serial_no=9599; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:13,459 [open_context_base.py] _handle_keep_alive:459: Fail to recv KeepAlive for 3 times\n",
      "2019-07-29 10:26:13,462 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:13,799 [open_context_base.py] on_connected:344: Connected : conn_id=25; \n",
      "2019-07-29 10:26:13,806 [open_context_base.py] on_connected:344: Connected : conn_id=24; \n",
      "2019-07-29 10:26:13,872 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=25; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431487368226952, 'conn_key': '5F0BA67E2CE30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:26:13,883 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=24; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431487383861959, 'conn_key': '0B88A57F2CE30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:26:14,317 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:14,368 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:21,466 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:22,373 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:26,594 [open_context_base.py] on_connect_timeout:385: Connect timeout: conn_id=27\n",
      "2019-07-29 10:26:26,603 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:27,467 [open_context_base.py] on_connect_timeout:385: Connect timeout: conn_id=28\n",
      "2019-07-29 10:26:27,473 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:29,452 [network_manager.py] _on_packet:562: Recv: conn_id=20; proto_id=1004; serial_no=9606; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:34,035 [network_manager.py] _on_packet:562: Recv: conn_id=25; proto_id=1004; serial_no=9607; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:34,039 [network_manager.py] _on_packet:562: Recv: conn_id=24; proto_id=1004; serial_no=9608; data_len=0; msg=Timeout;\n",
      "2019-07-29 10:26:34,611 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:34,698 [open_context_base.py] on_error:365: Connect error: conn_id=29; err=[Errno 11001] getaddrinfo failed;\n",
      "2019-07-29 10:26:34,702 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:35,482 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:35,518 [open_context_base.py] on_error:365: Connect error: conn_id=30; err=[Errno 11001] getaddrinfo failed;\n",
      "2019-07-29 10:26:35,529 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:35,961 [open_context_base.py] on_error:365: Connect error: conn_id=25; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:35,965 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:36,101 [open_context_base.py] on_error:365: Connect error: conn_id=20; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:36,104 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:36,258 [open_context_base.py] on_error:365: Connect error: conn_id=25; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:36,264 [open_context_base.py] on_error:365: Connect error: conn_id=24; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:36,267 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:36,432 [open_context_base.py] on_error:365: Connect error: conn_id=24; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:26:42,710 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:43,374 [open_context_base.py] on_connected:344: Connected : conn_id=31; \n",
      "2019-07-29 10:26:43,427 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=31; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431611411120637, 'conn_key': '41103D6049E30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:26:43,534 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:43,574 [open_context_base.py] on_connected:344: Connected : conn_id=32; \n",
      "2019-07-29 10:26:43,627 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=32; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431612261787890, 'conn_key': '848DEB9249E30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 10:26:44,103 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:44,121 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:44,258 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:44,295 [open_context_base.py] on_connected:344: Connected : conn_id=34; \n",
      "2019-07-29 10:26:44,360 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=34; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431615279612910, 'conn_key': '9480EF464AE30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:26:44,431 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:44,449 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:52,126 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:52,197 [open_context_base.py] on_connected:344: Connected : conn_id=36; \n",
      "2019-07-29 10:26:52,259 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=36; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431648395274833, 'conn_key': '8995BBFC51E30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:26:52,455 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:26:52,541 [open_context_base.py] on_connected:344: Connected : conn_id=37; \n",
      "2019-07-29 10:26:52,599 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=37; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561431649869905029, 'conn_key': '38A6BD5452E30E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:34:28,456 [open_context_base.py] on_error:365: Connect error: conn_id=37; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:34:28,459 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:28,477 [open_context_base.py] on_error:365: Connect error: conn_id=34; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:34:28,480 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:28,492 [open_context_base.py] on_error:365: Connect error: conn_id=31; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:34:28,496 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:28,512 [open_context_base.py] on_error:365: Connect error: conn_id=32; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:34:28,515 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:28,531 [open_context_base.py] on_error:365: Connect error: conn_id=36; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:34:28,533 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:28,568 [open_context_base.py] on_error:365: Connect error: conn_id=37; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 10:34:36,476 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:36,522 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:36,522 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:36,526 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:36,555 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:36,567 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:36,603 [open_context_base.py] on_connected:344: Connected : conn_id=39; \n",
      "2019-07-29 10:34:36,606 [open_context_base.py] on_connected:344: Connected : conn_id=40; \n",
      "2019-07-29 10:34:36,621 [open_context_base.py] on_connected:344: Connected : conn_id=42; \n",
      "2019-07-29 10:34:36,624 [open_context_base.py] on_connected:344: Connected : conn_id=41; \n",
      "2019-07-29 10:34:36,669 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=39; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561433596187557755, 'conn_key': '62D1317E17E50E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:34:36,695 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=40; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561433596373693873, 'conn_key': '3351268917E50E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:34:36,705 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=41; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561433596403601916, 'conn_key': 'F81FF78A17E50E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:34:36,711 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=42; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561433596530427160, 'conn_key': '00689D9217E50E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 10:34:44,586 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 10:34:44,661 [open_context_base.py] on_connected:344: Connected : conn_id=43; \n",
      "2019-07-29 10:34:44,711 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=43; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561433630061396326, 'conn_key': '4EA70B611FE50E5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:19:45,849 [open_context_base.py] on_error:365: Connect error: conn_id=43; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:19:45,874 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:45,957 [open_context_base.py] on_error:365: Connect error: conn_id=40; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:19:45,964 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:46,011 [open_context_base.py] on_error:365: Connect error: conn_id=43; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:19:46,016 [open_context_base.py] on_error:365: Connect error: conn_id=39; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:19:46,020 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:46,051 [open_context_base.py] on_error:365: Connect error: conn_id=42; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:19:46,054 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:46,085 [open_context_base.py] on_error:365: Connect error: conn_id=41; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:19:46,094 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:53,957 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:54,012 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:54,016 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:54,055 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 14:19:54,096 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:54,120 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:19:54,617 [open_context_base.py] on_connected:344: Connected : conn_id=46; \n",
      "2019-07-29 14:19:54,628 [open_context_base.py] on_connected:344: Connected : conn_id=45; \n",
      "2019-07-29 14:19:54,631 [open_context_base.py] on_connected:344: Connected : conn_id=47; \n",
      "2019-07-29 14:19:54,635 [open_context_base.py] on_connected:344: Connected : conn_id=48; \n",
      "2019-07-29 14:19:54,696 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=48; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490295196700277, 'conn_key': 'D68254C2A8180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:19:54,700 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=46; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490295160524550, 'conn_key': 'DC8F0DC0A8180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:19:54,707 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=45; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490295206747749, 'conn_key': '5A97E4C2A8180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:19:54,711 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=47; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490295184334618, 'conn_key': '82268BC1A8180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:20:02,048 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:02,113 [open_context_base.py] on_connected:344: Connected : conn_id=49; \n",
      "2019-07-29 14:20:02,174 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=49; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490326635678598, 'conn_key': '09C26414B0180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:20:34,822 [open_context_base.py] on_error:365: Connect error: conn_id=45; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:34,825 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:34,988 [open_context_base.py] on_error:365: Connect error: conn_id=47; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:34,992 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:35,069 [open_context_base.py] on_error:365: Connect error: conn_id=48; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:35,072 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:35,176 [open_context_base.py] on_error:365: Connect error: conn_id=46; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:35,179 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:35,247 [open_context_base.py] on_error:365: Connect error: conn_id=45; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:35,251 [open_context_base.py] on_error:365: Connect error: conn_id=49; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:35,254 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:35,289 [network_manager.py] do_send:326: Send error: conn_id=46; msg=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:35,292 [network_manager.py] do_send:326: Send error: conn_id=48; msg=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:20:42,985 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:43,000 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:43,069 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:43,176 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:43,247 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:43,322 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:44,138 [open_context_base.py] on_connected:344: Connected : conn_id=52; \n",
      "2019-07-29 14:20:44,141 [open_context_base.py] on_connected:344: Connected : conn_id=54; \n",
      "2019-07-29 14:20:44,225 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=52; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490502998628703, 'conn_key': 'B7364024D9180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:20:44,239 [open_context_base.py] on_connected:344: Connected : conn_id=51; \n",
      "2019-07-29 14:20:44,242 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=54; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490502998061998, 'conn_key': '7C076624D9180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:20:44,245 [open_context_base.py] on_connected:344: Connected : conn_id=53; \n",
      "2019-07-29 14:20:44,301 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=53; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490503303506961, 'conn_key': '41AB8D36D9180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:20:44,306 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=51; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490503310100226, 'conn_key': '5F80D436D9180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:20:51,003 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:20:51,082 [open_context_base.py] on_connected:344: Connected : conn_id=55; \n",
      "2019-07-29 14:20:51,140 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=55; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561490532008989865, 'conn_key': 'BA867CE5DF180F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:32:43,204 [network_manager.py] _on_packet:562: Recv: conn_id=52; proto_id=1004; serial_no=18777; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:43,417 [network_manager.py] _on_packet:562: Recv: conn_id=54; proto_id=1004; serial_no=18778; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:43,736 [network_manager.py] _on_packet:562: Recv: conn_id=51; proto_id=1004; serial_no=18779; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:43,743 [network_manager.py] _on_packet:562: Recv: conn_id=53; proto_id=1004; serial_no=18780; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:50,302 [network_manager.py] _on_packet:562: Recv: conn_id=55; proto_id=1004; serial_no=18781; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:51,242 [network_manager.py] _on_packet:562: Recv: conn_id=52; proto_id=1004; serial_no=18782; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:51,452 [network_manager.py] _on_packet:562: Recv: conn_id=54; proto_id=1004; serial_no=18783; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:51,767 [network_manager.py] _on_packet:562: Recv: conn_id=51; proto_id=1004; serial_no=18784; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:51,773 [network_manager.py] _on_packet:562: Recv: conn_id=53; proto_id=1004; serial_no=18785; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:53,278 [open_context_base.py] on_error:365: Connect error: conn_id=53; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:32:53,286 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:32:53,297 [open_context_base.py] on_error:365: Connect error: conn_id=53; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 14:32:53,305 [open_context_base.py] on_error:365: Connect error: conn_id=51; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:32:53,315 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:32:57,428 [open_context_base.py] on_error:365: Connect error: conn_id=55; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:32:57,435 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:32:57,449 [open_context_base.py] on_error:365: Connect error: conn_id=55; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:32:59,309 [network_manager.py] _on_packet:562: Recv: conn_id=52; proto_id=1004; serial_no=18787; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:59,316 [open_context_base.py] _handle_keep_alive:459: Fail to recv KeepAlive for 3 times\n",
      "2019-07-29 14:32:59,323 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:32:59,521 [network_manager.py] _on_packet:562: Recv: conn_id=54; proto_id=1004; serial_no=18788; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:32:59,528 [open_context_base.py] _handle_keep_alive:459: Fail to recv KeepAlive for 3 times\n",
      "2019-07-29 14:32:59,531 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:01,295 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:01,352 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:01,409 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:05,446 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:05,503 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:07,336 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:07,539 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:09,431 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:13,417 [open_context_base.py] on_error:365: Connect error: conn_id=56; err=[Errno 11001] getaddrinfo failed;\n",
      "2019-07-29 14:33:13,427 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:13,505 [open_context_base.py] on_connected:344: Connected : conn_id=57; \n",
      "2019-07-29 14:33:13,510 [open_context_base.py] on_connected:344: Connected : conn_id=59; \n",
      "2019-07-29 14:33:13,514 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:13,552 [open_context_base.py] on_connected:344: Connected : conn_id=60; \n",
      "2019-07-29 14:33:13,583 [open_context_base.py] on_connected:344: Connected : conn_id=62; \n",
      "2019-07-29 14:33:13,600 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=59; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561493646009774505, 'conn_key': '80705AEEB41B0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:33:13,607 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=57; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561493645980981383, 'conn_key': '27B181ECB41B0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:33:13,613 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=60; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561493645996730868, 'conn_key': 'EB66B6EDB41B0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:33:13,634 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=62; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561493646282870114, 'conn_key': '4F509EFEB41B0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:33:21,449 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:33:21,508 [open_context_base.py] on_connected:344: Connected : conn_id=63; \n",
      "2019-07-29 14:33:21,555 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=63; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561493679527859176, 'conn_key': 'E4A701BCBC1B0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:41:44,014 [network_manager.py] _on_packet:562: Recv: conn_id=63; proto_id=1004; serial_no=19103; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:41:44,123 [network_manager.py] _on_packet:562: Recv: conn_id=57; proto_id=1004; serial_no=19105; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:41:44,135 [network_manager.py] _on_packet:562: Recv: conn_id=59; proto_id=1004; serial_no=19104; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:41:44,144 [network_manager.py] _on_packet:562: Recv: conn_id=60; proto_id=1004; serial_no=19106; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:41:44,152 [network_manager.py] _on_packet:562: Recv: conn_id=62; proto_id=1004; serial_no=19107; data_len=0; msg=Timeout;\n",
      "2019-07-29 14:41:51,143 [open_context_base.py] on_error:365: Connect error: conn_id=63; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,149 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:51,160 [open_context_base.py] on_error:365: Connect error: conn_id=63; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,208 [open_context_base.py] on_error:365: Connect error: conn_id=59; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,215 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:51,229 [open_context_base.py] on_error:365: Connect error: conn_id=59; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,268 [open_context_base.py] on_error:365: Connect error: conn_id=57; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,273 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:51,282 [open_context_base.py] on_error:365: Connect error: conn_id=62; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,289 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:51,297 [open_context_base.py] on_error:365: Connect error: conn_id=57; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,304 [open_context_base.py] on_error:365: Connect error: conn_id=60; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:41:51,310 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,158 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,211 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,232 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,262 [open_context_base.py] on_connected:344: Connected : conn_id=64; \n",
      "2019-07-29 14:41:59,270 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,286 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,325 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,325 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 14:41:59,353 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:41:59,380 [open_context_base.py] on_connected:344: Connected : conn_id=66; \n",
      "2019-07-29 14:41:59,401 [open_context_base.py] on_connected:344: Connected : conn_id=67; \n",
      "2019-07-29 14:41:59,408 [open_context_base.py] on_connected:344: Connected : conn_id=68; \n",
      "2019-07-29 14:41:59,447 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=67; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561495851754534345, 'conn_key': '55962F7FB61D0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:41:59,457 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=68; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561495851793685592, 'conn_key': 'A75F7181B61D0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:42:07,264 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:42:07,315 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:42:07,382 [open_context_base.py] on_connected:344: Connected : conn_id=70; \n",
      "2019-07-29 14:42:07,385 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:42:07,413 [open_context_base.py] on_connected:344: Connected : conn_id=69; \n",
      "2019-07-29 14:42:07,532 [open_context_base.py] on_connected:344: Connected : conn_id=71; \n",
      "2019-07-29 14:42:07,660 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=69; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561495885267162611, 'conn_key': '6B6DB74CBE1D0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:42:07,673 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=70; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561495885218361835, 'conn_key': '9CAB8F49BE1D0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:42:07,687 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=71; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561495885817396093, 'conn_key': '91D57B6DBE1D0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:46:11,986 [open_context_base.py] on_error:365: Connect error: conn_id=70; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:11,988 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:12,155 [open_context_base.py] on_error:365: Connect error: conn_id=68; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:12,159 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:12,282 [open_context_base.py] on_error:365: Connect error: conn_id=70; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:12,286 [open_context_base.py] on_error:365: Connect error: conn_id=71; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:12,289 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:12,350 [open_context_base.py] on_error:365: Connect error: conn_id=67; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:12,353 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:12,400 [open_context_base.py] on_error:365: Connect error: conn_id=69; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:12,403 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,154 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,172 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,282 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,325 [open_context_base.py] on_connected:344: Connected : conn_id=73; \n",
      "2019-07-29 14:46:20,350 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,378 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=73; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561496946162719767, 'conn_key': '0C3EDD4EB51E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:46:20,386 [open_context_base.py] on_connected:344: Connected : conn_id=74; \n",
      "2019-07-29 14:46:20,400 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,432 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:20,447 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=74; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561496946393266883, 'conn_key': '23F6885CB51E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:46:20,453 [open_context_base.py] on_connected:344: Connected : conn_id=75; \n",
      "2019-07-29 14:46:20,484 [open_context_base.py] on_connected:344: Connected : conn_id=76; \n",
      "2019-07-29 14:46:20,511 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=75; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561496946642609454, 'conn_key': '655B546BB51E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:46:20,539 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=76; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561496946847002044, 'conn_key': '6162BA77B51E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:46:28,179 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:28,219 [open_context_base.py] on_connected:344: Connected : conn_id=77; \n",
      "2019-07-29 14:46:28,285 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=77; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561496979260468059, 'conn_key': '61C9B303BD1E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:46:57,491 [open_context_base.py] on_error:365: Connect error: conn_id=73; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:57,500 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:57,550 [open_context_base.py] on_error:365: Connect error: conn_id=76; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:57,554 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:57,571 [open_context_base.py] on_error:365: Connect error: conn_id=75; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:57,575 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:46:57,624 [open_context_base.py] on_error:365: Connect error: conn_id=73; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:57,628 [open_context_base.py] on_error:365: Connect error: conn_id=74; err=[WinError 10054] 远程主机强迫关闭了一个现有的连接。;\n",
      "2019-07-29 14:46:57,630 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:47:05,549 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:47:05,601 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:47:05,632 [open_context_base.py] _wait_reconnect:473: Wait reconnect in 8 seconds: host=futuapi.mkmerich.com; port=54012;\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-07-29 14:47:05,632 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:47:05,650 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:47:05,670 [open_context_base.py] on_connected:344: Connected : conn_id=79; \n",
      "2019-07-29 14:47:05,690 [open_context_base.py] on_connected:344: Connected : conn_id=80; \n",
      "2019-07-29 14:47:05,693 [open_context_base.py] on_connected:344: Connected : conn_id=81; \n",
      "2019-07-29 14:47:05,728 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=79; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561497136358140342, 'conn_key': '3BA96997E11E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:47:05,744 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=81; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561497136463356087, 'conn_key': 'B628BE9DE11E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:47:05,752 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=80; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561497136428343421, 'conn_key': '37CC859BE11E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n",
      "2019-07-29 14:47:13,649 [open_context_base.py] _socket_reconnect_and_wait_ready:256: Start connecting: host=futuapi.mkmerich.com; port=54012;\n",
      "2019-07-29 14:47:13,701 [open_context_base.py] on_connected:344: Connected : conn_id=82; \n",
      "2019-07-29 14:47:13,774 [open_context_base.py] _handle_init_connect:444: InitConnect ok: conn_id=82; info={'server_version': 203, 'login_user_id': 1509176, 'conn_id': 6561497170102257722, 'conn_key': '6E2AB172E91E0F5B', 'keep_alive_interval': 10, 'is_encrypt': False};\n"
     ]
    }
   ],
   "source": [
    "data"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
